### ISSUE TITLE
Check for cache directory exists before write

### ISSUE THREAD

**Issue by okelet** [aidanmelen/awscli_bastion#4]
* awscli_bastion version: 0.8.3
* Python version: 3.6.9
* Operating System: Ubuntu 18.04

### Description

Just installed and configured, when first login, the command fails:

```
Enter MFA code for arn:aws:iam::xxx:mfa/xx:

Error when retrieving credentials from custom-process: Traceback (most recent call last):
  File "/home/okelet/.local/bin/bastion", line 11, in <module>
    sys.exit(main())
  File "/home/okelet/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/okelet/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/okelet/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/okelet/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/okelet/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/okelet/.local/lib/python3.6/site-packages/awscli_bastion/cli.py", line 43, in get_session_token
    sts_creds = sts.get_session_token(mfa_code=mfa_code, mfa_serial=mfa_serial, duration_seconds=duration_seconds)
  File "/home/okelet/.local/lib/python3.6/site-packages/awscli_bastion/sts.py", line 85, in get_session_token
    self.cache.write(sts_creds)
  File "/home/okelet/.local/lib/python3.6/site-packages/awscli_bastion/cache.py", line 72, in write
    with open(self.bastion_sts_cache_path, 'w+') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/okelet/.aws/cli/cache/bastion-sts.json'
```

### What I Did

```
aws sts get-caller-identity --profile xxx
```

**Comment by aidan-melen** [comment]
So that is a `FileNotFoundError`. Can you check that the` /home/okelet/.aws/cli/cache` directory exists? That should have been created for you.

**Comment by aidan-melen** [comment]
**Fix:**
Create the missing directory: `/home/okelet/.aws/cli/cache`

**Explanation:**
So the cache directory is actually created and managed by the `awscli` when you assume a role. `awscli-bastion` just so happens to uses this directory but assumes that the `awscli` has already created it... but it probably wouldn't hurt to just create the cache directory if it doesn't already exist.

**More Context:**
```
When you specify a profile that has IAM role configuration, the AWS CLI will make an AssumeRole call to retrieve temporary credentials. These credentials are then stored (in ~/.aws/cli/cache). Subsequent AWS CLI commands will use the cached temporary credentials until they expire, in which case the AWS CLI will automatically refresh credentials.
```

https://docs.aws.amazon.com/cli/latest/topic/config-vars.html

**Comment by aidanmelen** [comment]
**Fix:**
Create the missing directory: `/home/okelet/.aws/cli/cache`

**Explanation:**
So the cache directory is actually created and managed by the awscli when you assume a role. awscli-bastion just so happens to uses this directory but assumes that the awscli has already created it... but it probably wouldn't hurt to just create the cache directory if it doesn't already exist.

**More Context:**

"When you specify a profile that has IAM role configuration, the AWS CLI will make an AssumeRole call to retrieve temporary credentials. These credentials are then stored (in ~/.aws/cli/cache). Subsequent AWS CLI commands will use the cached temporary credentials until they expire, in which case the AWS CLI will automatically refresh credentials." and `awscli-bastion` works the same way.

https://docs.aws.amazon.com/cli/latest/topic/config-vars.html

**Comment by okelet** [comment]
Hi @aidanmelen , the directory didn't exist, I had to create it manually.
